Repository GoldElysium/hef-website, pull requests merged in 2021-05, with the labels that each got.

#59 feature(JIT): Enable JIT and add ESLint stuff
  .eslintignore
  .github/workflows/eslint.yml
  .husky/.gitignore
  .husky/pre-commit
  commitlint.config.js
  components/DarkModeToggle.tsx
  components/Navbar.tsx
  contexts/DarkModeContext.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  tailwind.config.js
Labels: enhancement

#63 chore(guidelines): Add several documents
  .github/workflows/codeql-analysis.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  SECURITY.md
Labels: documentation

#61 fix(ProjectEditPage): Markdown editor value fixed
  components/ProjectEditPage.tsx
Labels: bug

#62 feature(Project): Improved submission system
  .eslintrc.js
  .gitignore
  components/Card.tsx
  components/ProjectEditPage.tsx
  models/Guild.ts
  models/Project.ts
  models/Setting.ts
  models/Submission.ts
  pages/api/admin/setting.ts
  pages/api/guilds/[id].ts
  pages/api/guilds/index.ts
  pages/api/projects/[id].ts
  pages/api/projects/index.ts
  pages/api/submissions/[id].ts
  pages/dashboard/guild/[id].tsx
  pages/dashboard/index.tsx
  pages/projects/[id].tsx
  pages/projects/index.tsx
Labels: enhancement

#73 fix(Project): use correct class
  pages/projects/[id].tsx
Labels: bug

#75 fix: fix post-merge hook
  .husky/post-merge
Labels: bug

#74 minor tweaks to some widths
  pages/projects/[id].tsx
Labels: enhancement

#77 fix(husky): this time tested
  .husky/post-merge
Labels: bug

#65 feat(Gallery text): add text support for the gallery
  .github/CODEOWNERS
  components/DashboardCard.tsx
  components/DashboardPage.tsx
  components/ProjectEditPage.tsx
  models/Project.ts
  pages/api/submissions/index.ts
  pages/projects/[id].tsx
Labels: bug, enhancement

#95 fix(Project): force codeblock text to black
  styles/globals.css
Labels: bug

#96 fix(Project): remove unused backslashes
  pages/projects/[id].tsx
Labels: bug

#93 Feature/submission expand
  models/Submission.ts
  package-lock.json
  package.json
  pages/projects/[id].tsx
Labels: enhancement
