Repository GoldElysium/hef-website, pull requests merged in 2022-08, with the labels that each got.

#303 Feature: Credits component for experimental project page
  components/project/experimental/Credit.tsx
  components/project/experimental/Credits.tsx
  components/project/experimental/Page.tsx
  models/Project.ts
  package-lock.json
  package.json
  styles/sana-timeline.css
Labels: Type: Feature, Component: Pages

#305 refactor: resolve all eslint issues and add id 18 to project page whitelist
  .eslintrc.js
  components/DashboardPage.tsx
  components/Footer.tsx
  components/GuildEditPage.tsx
  components/Header.tsx
  components/Navbar.tsx
  components/NoticeBanner.tsx
  components/ProjectEditPage.tsx
  components/phaser/guratanabata/fullPaper.tsx
  components/phaser/guratanabata/index.tsx
  components/phaser/guratanabata/info.tsx
  components/phaser/guratanabata/main.tsx
  components/phaser/guratanabata/plugins/ui.tsx
  components/phaser/guratanabata/splash.tsx
  components/project/BlurBackground.tsx
  components/project/Description.tsx
  components/project/Gallery.tsx
  components/project/Links.tsx
  components/project/Phaser.tsx
  components/project/Submissions.tsx
  components/project/experimental/About.tsx
  components/project/experimental/BackgroundMusic.tsx
  components/project/experimental/Credit.tsx
  components/project/experimental/Credits.tsx
  components/project/experimental/Links.tsx
  components/project/experimental/Page.tsx
  components/project/experimental/Tab.tsx
  components/project/experimental/Tabs.tsx
  components/project/experimental/Timeline.tsx
  contexts/SupportContext.tsx
  pages/_app.tsx
  pages/api/admin/setting.ts
  pages/dashboard/guild/[id].tsx
  pages/dashboard/index.tsx
  pages/dashboard/project/[id].tsx
  pages/index.tsx
  pages/projects/[id].tsx
  pages/projects/index.tsx
Labels: Priority: High, Type: Refactor, Component: Pages, Component: Dashboard

#306 fix(sana-sendoff): add missing spaces in timeline
  components/project/experimental/Timeline.tsx
Labels: Component: Pages
