Repository GoldElysium/hef-website, pull requests merged in 2023-04, with the labels that each got.

#353 Update to Next.js 13.3
  .npmrc
  package.json
  pnpm-lock.yaml
  src/app/sitemap.ts
Labels: Type: Enhancement, Priority: Low

#354 Fix guratanabata
  src/ui/project/guratanabata/PhaserSubmissionWrapper.tsx
  src/ui/project/guratanabata/phaserScene/index.ts
  src/ui/project/guratanabata/phaserScene/main.ts
Labels: Type: Bug, Priority: High, Component: Pages

#337 feat(i18n): add i18n support
  package.json
  pnpm-lock.yaml
  public/locales/en/default.json
  public/locales/en/home.json
  public/locales/en/layout.json
  public/locales/en/project.json
  public/locales/en/projects.json
  public/locales/jp/default.json
  src/app/(DynamicLayout)/projects/[slug]/page.tsx
  src/app/(StaticLayout)/page.tsx
  src/app/(StaticLayout)/projects/page.tsx
  src/app/[lang]/(DynamicLayout)/projects/[slug]/layout.tsx
  src/app/[lang]/(DynamicLayout)/projects/[slug]/loading.tsx
  src/app/[lang]/(DynamicLayout)/projects/[slug]/page.tsx
  src/app/[lang]/(StaticLayout)/layout.tsx
  src/app/[lang]/(StaticLayout)/loading.tsx
  src/app/[lang]/(StaticLayout)/page.tsx
  src/app/[lang]/(StaticLayout)/projects/loading.tsx
  src/app/[lang]/(StaticLayout)/projects/page.tsx
  src/app/[lang]/layout.tsx
  src/app/layout.tsx
  src/app/sitemap.ts
  src/app/sitemap.xml/route.ts
  src/contexts/LocaleContext.tsx
  src/lib/i18n/client.ts
  src/lib/i18n/languages.ts
  src/lib/i18n/server.ts
  src/lib/i18n/settings.ts
  src/lib/util/localizePathname.ts
  src/lib/util/middleware.ts
  src/middleware.ts
  src/ui/Card.tsx
  src/ui/Hero.tsx
  src/ui/LocaleContextProvider.tsx
  src/ui/LocaleSelect.tsx
  src/ui/Navbar.tsx
  src/ui/NavbarMenu.tsx
  src/ui/NoticeBanner.tsx
  src/ui/project/GalleryItem.tsx
  src/ui/project/Submission.tsx
  src/ui/project/Submissions.tsx
  src/ui/project/experimental/sana/DarkModeFlag.tsx
  src/ui/project/experimental/sana/Page.tsx
Labels: Priority: Medium, Type: Feature, Component: Pages
