Repository GoldElysium/hef-website, pull requests merged in 2023-03, with the labels that each got.

#333 feat: Extended submissions
  .github/workflows/codeql-analysis.yml
  .github/workflows/eslint.yml
  app/(DynamicLayout)/projects/[slug]/head.tsx
  app/(DynamicLayout)/projects/[slug]/page.tsx
  app/(StaticLayout)/head.tsx
  app/(StaticLayout)/projects/head.tsx
  app/(StaticLayout)/projects/page.tsx
  app/layout.tsx
  next-env.d.ts
  package.json
  pnpm-lock.yaml
  types/payload-types.ts
  ui/Head.tsx
  ui/project/Submission.tsx
  ui/project/SubmissionGallery.tsx
  ui/project/Submissions.tsx
  ui/project/experimental/sana/About.tsx
  ui/project/experimental/sana/BackgroundMusic.tsx
  ui/project/experimental/sana/Credit.tsx
  ui/project/experimental/sana/Credits.tsx
  ui/project/experimental/sana/DarkModeFlag.tsx
  ui/project/experimental/sana/Description.tsx
  ui/project/experimental/sana/Links.tsx
  ui/project/experimental/sana/Page.tsx
  ui/project/experimental/sana/Submissions.tsx
  ui/project/experimental/sana/Tab.tsx
  ui/project/experimental/sana/Tabs.tsx
  ui/project/experimental/sana/TextHeader.tsx
  ui/project/experimental/sana/Timeline.tsx
  ui/project/experimental/submissionsFilter/SubmissionsWithFilter.tsx
Labels: Type: Enhancement, Priority: High, Component: Pages

#331 fix(dotenv): update CMS public url env var
  .env.example
Labels: Type: Miscellaneous

#310 chore(timeline): added Sana's appearance in Rise
  .all-contributorsrc
  README.md
  ui/project/experimental/sana/Timeline.tsx
Labels: Priority: Low, Component: Pages, Type: Miscellaneous
