Repository GoldElysium/hef-website, pull requests merged in 2024-07, with the labels that each got.

#402 Feat/KiaraBday2024
  src/app/[lang]/(DynamicLayout)/projects/[slug]/page.tsx
  src/components/ui/project/kiarabday/KiaraBdaySubmissionWrapper.tsx
Labels: Type: Enhancement, Type: Feature, Component: Design, Component: Pages

#405 AnniversaRyS 2024
  package.json
  pnpm-lock.yaml
  postcss.config.js
  public/locales/en/reader.json
  public/locales/jp/reader.json
  src/app/[lang]/(DynamicLayout)/projects/[slug]/page.tsx
  src/app/[lang]/layout.tsx
  src/components/ui/legacy/Image.tsx
  src/components/ui/project/irysmanga/HeaderIcons.tsx
  src/components/ui/project/irysmanga/IrysManga.tsx
  src/components/ui/project/irysmanga/IrysMangaDataWrapper.tsx
  src/components/ui/project/irysmanga/KeyPressHandler.tsx
  src/components/ui/project/irysmanga/LoadingIcon.tsx
  src/components/ui/project/irysmanga/ProgressBar.tsx
  src/components/ui/project/irysmanga/Reader.tsx
  src/components/ui/project/irysmanga/ReaderHeader.tsx
  src/components/ui/project/irysmanga/ReaderSidebar.tsx
  src/components/ui/project/irysmanga/SelectBox.tsx
  src/components/ui/project/irysmanga/SettingButton.tsx
  src/components/ui/project/irysmanga/context/MangaContext.tsx
  src/components/ui/project/irysmanga/modal-components/CreditBlock.tsx
  src/components/ui/project/irysmanga/modal-components/FloatingDecoArt.tsx
  src/components/ui/project/irysmanga/modal-components/FloatingDecoArtDraggable.tsx
  src/components/ui/project/irysmanga/modal-components/ModalTab.tsx
  src/components/ui/project/irysmanga/modal-components/ModalTabContent.tsx
  src/components/ui/project/irysmanga/modal-components/ModalTabGeneral.tsx
  src/components/ui/project/irysmanga/modal-components/ModalTabLicences.tsx
  src/components/ui/project/irysmanga/modal-components/ModalTabReader.tsx
  src/components/ui/project/irysmanga/modal-components/ModalTabStory.tsx
  src/components/ui/project/irysmanga/modal-components/ReaderModal.tsx
  src/components/ui/project/irysmanga/modal-components/ThemeController.tsx
  src/components/ui/project/irysmanga/styles/Header.module.css
  src/components/ui/project/irysmanga/styles/ProgressBar.module.css
  src/components/ui/project/irysmanga/styles/Reader.module.css
  src/components/ui/project/irysmanga/styles/Sidebar.module.css
  src/components/ui/project/irysmanga/styles/styles.css
  src/components/ui/project/irysmanga/utils/data-helper.ts
  src/components/ui/project/irysmanga/utils/helper.ts
  src/components/ui/project/irysmanga/utils/types.ts
  src/components/ui/project/kroniipuzzle/pixi/Modal.tsx
  src/components/ui/project/kroniipuzzle/pixi/PieceDisplay.tsx
  tailwind.config.js
Labels: Priority: High, Type: Feature, Component: Pages

#407 fix: Fix a bunch of irys manga issues
  src/components/ui/project/irysmanga/Reader.tsx
  src/components/ui/project/irysmanga/modal-components/ModalTabStory.tsx
Labels: Type: Bug, Component: Pages
